icons_format = "{icon}"

[theme]
theme = "ctp-mocha"

[icons]
icons = "material-nf"

[[block]]
block = "vpn"
driver = "mullvad"
interval = 10
format_connected = "VPN: $icon "
format_disconnected = "VPN: $icon "
state_connected = "good"
state_disconnected = "warning"

[[block]]
block = "external_ip"
interval = 5
format = " $ip $country_code"

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min $max max $average avg "
interval = 2
chip = "k10temp-pci-00c3"

[[block]]
block = "memory"
interval = 1
format = " $icon $mem_used_percents.eng(w:1) "
warning_mem = 70
critical_mem = 90

[[block]]
block = "load"
format = " $icon $1m.eng(w:4) "
interval = 1

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "


[[block]]
block = "sound"

[[block.click]]
button = "left"
cmd = "pavucontrol"


[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a: %d/%m %R') "
